### PR TITLE
docs(readme): update image url

### PR DESCRIPTION
**Pull request by keithkade**
Move to the new cms

### CODE REVIEW

**Comment by jmeis** [comment]
@keithkade Can you make these PRs to the `development` branch first?

**Comment by keithkade** [comment]
@jmeis Is changing the base ok, or should I open up a fresh PR?

**Review by nfstein — APPROVED** [review]

**Comment by jmeis** [comment]
@keithkade I think it might be better to open a fresh PR.

**Comment by keithkade** [comment]
Opened up a new PR https://github.com/IBM/python-flask-app/pull/63

**Pull request closed without merging**
